name: Build Kujang Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Show Environment
        run: |
          echo "Repository : $GITHUB_REPOSITORY"
          echo "Branch : $GITHUB_REF_NAME"
          uname -a
